import pygame

# Game settings
WIDTH = 1200
HEIGHT = 700
CAPTION = "STUNNERS GAME"
FPS = 60


# Player settings
#------------------
# COINS
START_COINS = 3
INCREASE_COINS_PER_TURN = 1
MAX_COINS = 10
BUY_MINION_COINS = 3
SALE_MINION_COINS = 1
REFRESH_STORE_COINS = 1
FREEZE_COINS = 0
#------------------
# TAVERN
#------------------
# GOLDEN, RECRUIT, DISCOVER
MAX_MINIOS_IN_HAND = 10


# ANIMATION (ms)
ATTACK_START = 220
DAMAGE_RESOLVE = 120
DEATHRATTLE_TRIGGLE = 300
SUMMON_DELAY = 80
REBORN_SPAWN = 260

